
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
from tkinter import ttk
import Final
import threading
import sys
import os

def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)

img_dir = resource_path("image_1.png")


def start():
    threading.Thread(target=setup,daemon=True).start()


def setup():
    port1=ScalePort.get()
    port2=PrinterPort.get()

    while True:
        Ref=Final.Auto(port1,port2,1)
        Mode.set(Ref)


window = Tk()

window.geometry("433x403")
window.configure(bg = "#232430")


canvas = Canvas(
    window,
    bg = "#232430",
    height = 403,
    width = 433,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    222.070068359375,
    32.41778564453125,
    anchor="nw",
    text="VALCO HAUL ROAD APP",
    fill="#FFFFFF",
    font=("Inter", 15 * -1)
)

canvas.create_text(
    43.0,
    126.0,
    anchor="nw",
    text="SCALE COM PORT",
    fill="#FFFFFF",
    font=("Inter", 15 * -1)
)

canvas.create_text(
    250.0,
    126.0,
    anchor="nw",
    text="PRINTER COM PORT",
    fill="#FFFFFF",
    font=("Inter", 15 * -1)
)

ScalePort=StringVar()
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    textvariable=ScalePort
)
entry_1.place(
    x=28.0,
    y=155.0,
    width=167.0,
    height=33.0
)


PrinterPort=StringVar()
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    textvariable=PrinterPort
)
entry_2.place(
    x=243.0,
    y=155.0,
    width=168.0,
    height=33.0
)

image_image_1 = PhotoImage(
    file=img_dir)
image_1 = canvas.create_image(
    105.0,
    52.0,
    image=image_image_1
)


button_1 = Button(
    borderwidth=0,
    highlightthickness=0,
    command=start,
    relief="flat",
    background="black",
    foreground="white",
    text="SETUP",
)
button_1.place(
    x=179.0,
    y=241.0,
    width=111.0,
    height=49.0
)



Mode=StringVar()
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    textvariable=Mode
)
entry_3.place(
    x=139.0,
    y=335.0,
    width=188.0,
    height=42.0
)

canvas.create_text(
    212.0,
    312.0,
    anchor="nw",
    text="MODE",
    fill="#FFFFFF",
    font=("Inter", 15 * -1)
)
window.resizable(False, False)
window.mainloop()
